Inventory/Controllers/ItemController.cs
using Inventory.Data;
using Inventory.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Inventory.Controllers
{
    public class ItemController : Controller
    {
        protected readonly AppDbContext _context;
        private readonly ILogger<ItemController> _logger;
        public ItemController(AppDbContext context, ILogger<ItemController> logger)
        {
            _context = context;
            _logger = logger;
        }

        [Authorize(Policy = "superadmin")]
        public async Task<IActionResult> Index()
        {
            var item = await _context.Items
                .Include(c => c.Category)
                .Include(u => u.Unit)
                .OrderByDescending(i => i.Id)
                .ToListAsync();
            return View(item);
        }

        [Authorize(Policy = "superadmin")]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_context.Categories.ToList(), "Id", "CategoryName");
            ViewBag.Units = new SelectList(_context.Units.ToList(), "Id", "UnitName");
            return View();
        }

        [Authorize(Policy = "superadmin")]
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id", "ItemName", "ItemDescription", "CategoryId", "UnitId")] Item item, IFormFile ItemImage)
        {
            if (!ModelState.IsValid)
            {
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    _logger.LogError("Model Error: {ErrorMessage}", error.ErrorMessage);
                }
            }

            // If validation is successful
            if (ModelState.IsValid)
            {
                // Storage folder location
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/item-image");

                // Create a folder if it doesn't exist yet
                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }

                // Generate unique filename
                string uniqueFileName = Guid.NewGuid().ToString() + Path.GetExtension(ItemImage.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                // Save to directory
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await ItemImage.CopyToAsync(fileStream);
                }

                // Save to path model
                item.ItemImage = $"/item-image/{uniqueFileName}";

                // Save to database
                item.CreatedAt = DateTime.Now;
                _context.Items.Add(item);
                await _context.SaveChangesAsync();

                TempData["SuccessMessage"] = "Item added successfully.";
                return RedirectToAction("Index");
            }

            // if failed valisation, return back into form
            ViewBag.Categories = new SelectList(_context.Categories.ToList(), "Id", "CategoryName");
            ViewBag.Units = new SelectList(_context.Units.ToList(), "Id", "UnitName");
            return View(item);
        }

        [Authorize(Policy = "superadmin")]
        public async Task<IActionResult> Edit(int id)
        {
            var item = await _context.Items.FirstOrDefaultAsync(x => x.Id == id);
            ViewBag.Categories = new SelectList(_context.Categories.ToList(), "Id", "CategoryName");
            ViewBag.Units = new SelectList(_context.Units.ToList(), "Id", "UnitName");

            return View(item) ;
        }

        [Authorize(Policy = "superadmin")]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id", "ItemName", "ItemDescription", "CategoryId", "UnitId")] Item item, IFormFile ItemImage)
        {
            if (item == null)
            {
                return NotFound();
            }

            if (ItemImage != null && ItemImage.Length > 0)
            {
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/item-image");
                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }

                string uniqueFileName = Guid.NewGuid().ToString() + Path.GetExtension(ItemImage.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await ItemImage.CopyToAsync(fileStream);
                }

                if (!string.IsNullOrEmpty(item.ItemImage))
                {
                    string oldFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", item.ItemImage.TrimStart('/'));

                    if (System.IO.File.Exists(oldFilePath))
                    {
                        System.IO.File.Delete(oldFilePath);
                    }

                }
                item.ItemImage = $"/item-image/{uniqueFileName}";
            }
            else
            {
                var existingItem = await _context.Items.AsNoTracking().FirstOrDefaultAsync(i => i.Id == id);
                if (existingItem != null)
                {
                    item.ItemImage = existingItem.ItemImage; 
                }
            }

            _context.Update(item);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Item updated successfully!";
            return RedirectToAction("Index");
        }

        [Authorize(Policy = "superadmin")]
        public async Task<IActionResult> Detail(int id)
        {
            var item = await _context.Items.FirstOrDefaultAsync(x => x.Id == id);
            ViewBag.Categories = new SelectList(_context.Categories.ToList(), "Id", "CategoryName");
            ViewBag.Units = new SelectList(_context.Units.ToList(), "Id", "UnitName");

            return View(item);
        }

        [Authorize(Policy = "superadmin")]
        public async Task<IActionResult> Delete(int id)
        {
            var item = await _context.Items.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }

            if (!string.IsNullOrEmpty(item.ItemImage))
            {
                string imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", item.ItemImage.TrimStart('/'));

                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }

            _context.Items.Remove(item);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Item deleted successfully!";
            return RedirectToAction("Index");
        }
    }
}

Inventory/Controllers/ItemOutController.cs
using Inventory.Data;
using Inventory.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Inventory.Controllers
{
    public class ItemOutController : Controller
    {
        protected readonly AppDbContext _context;
        public ItemOutController(AppDbContext context)
        {
            _context = context;
        }

        [Authorize(Policy = "superadminOrAdmin")]
        public async Task<IActionResult> Index()
        {
            var itemOut = await _context.ItemsOut
                .Include(i => i.Item)
                .Include(c => c.Customer)
                .ToListAsync();
            return View(itemOut);
        }

        [Authorize(Policy = "superadminOrAdmin")]
        public IActionResult Create()
        {
            ViewBag.Items = new SelectList(_context.Items.ToList(), "Id", "ItemName");
            ViewBag.Customers = new SelectList(_context.Customers.ToList(), "Id", "CustomerName");
            return View();
        }

        [Authorize(Policy = "superadminOrAdmin")]
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id", "ItemId", "DateOfEntry", "StockOut", "CustomerId")] ItemOut itemOut)
        {
            if (ModelState.IsValid)
            {
                var random = new Random();
                int randomNumber = random.Next(10000, 99999);
                itemOut.TransactionCode = $"INV-{randomNumber}";

                var item = await _context.Items.FirstOrDefaultAsync(i => i.Id == itemOut.ItemId);
                if (item == null)
                {
                    ModelState.AddModelError("ItemId", "The selected item does not exist.");
                    ViewBag.Items = new SelectList(_context.Items.ToList(), "Id", "ItemName", itemOut.ItemId);
                    return View(itemOut);
                }

                if (itemOut.StockOut > item.ItemStock)
                {
                    ModelState.AddModelError("StockOut", "Stock out cannot exceed available ItemStock.");
                    ViewBag.Items = new SelectList(_context.Items.ToList(), "Id", "ItemName", itemOut.ItemId);
                    ViewBag.Customers = new SelectList(_context.Customers.ToList(), "Id", "CustomerName", itemOut.CustomerId);
                    return View(itemOut);
                }

                using (var transaction = await _context.Database.BeginTransactionAsync())
                {
                    {
                        _context.Add(itemOut);
                        await _context.SaveChangesAsync();

                        item.ItemStock -= itemOut.StockOut;
                        _context.Items.Update(item);
                        await _context.SaveChangesAsync();

                        await transaction.CommitAsync();

                        TempData["SuccessMessage"] = "Item successfully added.";
                        return RedirectToAction("Index");
                    }
                }
            }
            ViewBag.Items = new SelectList(_context.Items.ToList(), "Id", "ItemName", itemOut.ItemId);
            ViewBag.Customers = new SelectList(_context.Customers.ToList(), "Id", "CustomerName", itemOut.CustomerId);
            return View(itemOut);
        }

        [Authorize(Policy = "superadminOrAdmin")]
        public async Task<IActionResult> Edit(int id)
        {
            var itemOut = await _context.ItemsOut.FirstOrDefaultAsync(x => x.Id == id);
            ViewBag.Items = new SelectList(_context.Items.ToList(), "Id", "ItemName");
            ViewBag.Customers = new SelectList(_context.Customers.ToList(), "Id", "CustomerName");

            return View(itemOut);
        }

        [Authorize(Policy = "superadminOrAdmin")]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id", "ItemId", "DateOfEntry", "StockOut", "CustomerId")] ItemOut itemOut)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Items = new SelectList(_context.Items.ToList(), "Id", "ItemName", itemOut.ItemId);
                ViewBag.Customers = new SelectList(_context.Customers.ToList(), "Id", "SupplierName", itemOut.CustomerId);
                return View(itemOut);
            }

            var existingStockOut = await _context.ItemsOut.FirstOrDefaultAsync(x => x.Id == id);
            if (existingStockOut == null)
            {
                return NotFound();
            }

            var item = await _context.Items.FirstOrDefaultAsync(i => i.Id == itemOut.ItemId);
            if (item == null)
            {
                TempData["ErrorMessage"] = "Item not found.";
                return RedirectToAction("Index");
            }

            int stockDifference = itemOut.StockOut - existingStockOut.StockOut;

            if (item.ItemStock - stockDifference < 0)
            {
                TempData["ErrorMessage"] = "Stock is insufficient for the requested update.";

                ViewBag.Items = new SelectList(_context.Items.ToList(), "Id", "ItemName", itemOut.ItemId);
                ViewBag.Customers = new SelectList(_context.Customers.ToList(), "Id", "SupplierName", itemOut.CustomerId);
                return View(itemOut);
            }

            item.ItemStock -= stockDifference;
            _context.Items.Update(item);

            _context.Entry(existingStockOut).CurrentValues.SetValues(itemOut);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Item Out updated successfully";
            return RedirectToAction("Index");
        }

        [Authorize(Policy = "superadminOrAdmin")]
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var itemOut = await _context.ItemsOut.FindAsync(id);
            if (itemOut == null)
            {
                return NotFound();
            }

            _context.ItemsOut.Remove(itemOut);
            await _context.SaveChangesAsync();

            var item = await _context.Items.FirstOrDefaultAsync(i => i.Id == itemOut.ItemId);
            if (item != null)
            {
                item.ItemStock += itemOut.StockOut;

                _context.Items.Update(item);
                await _context.SaveChangesAsync();
            }

            TempData["SuccessMessage"] = "Incoming Item deleted successfully!";
            return RedirectToAction("Index");
        }
    }
}

Inventory/Controllers/UnitController.cs
using Inventory.Data;
using Inventory.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Inventory.Controllers
{
    public class UnitController : Controller
    {
        protected readonly AppDbContext _context;
        public UnitController(AppDbContext context)
        {
            _context = context;
        }

        [Authorize(Policy = "superadmin")]

        public async Task<IActionResult> Index()
        {
            var unit = await _context.Units
                .OrderByDescending(u => u.Id)
                .ToListAsync();
            return View(unit);
        }

        [Authorize(Policy = "superadmin")]

        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Policy = "superadmin")]

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id", "UnitName")] Unit unit)
        {
            if (ModelState.IsValid)
            {
                _context.Units.Add(unit);
                await _context.SaveChangesAsync();

                TempData["SuccessMessage"] = "Unit added successfully";
                return RedirectToAction("Index");
            }
            return View(unit);
        }

        [Authorize(Policy = "superadmin")]

        public async Task<IActionResult> Edit(int id)
        {
            var unit = await _context.Units.FirstOrDefaultAsync(x=>x.Id == id);
            return View(unit);
        }

        [Authorize(Policy = "superadmin")]

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id", "UnitName")] Unit unit)
        {
            if (ModelState.IsValid)
            {
                _context.Update(unit);
                await _context.SaveChangesAsync();

                TempData["SuccessMessage"] = "Unit updated successfully";
                return RedirectToAction("Index");
            }
            return View(unit);
        }

        [Authorize(Policy = "superadmin")]

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var unit = await _context.Units.FindAsync(id);
            if(unit == null)
            {
                return NotFound();
            }

            _context.Units.Remove(unit);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Unit deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

Inventory/Views/Shared/_AuthLayout.cshtml

<!DOCTYPE html>
<html dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="/assets/image/png" sizes="16x16" href="assets/images/favicon.png">
    <title>Auth</title>
    <!-- Custom CSS -->
    <link href="/assets/css/style.min.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <div class="main-wrapper">
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
 
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        @RenderBody()
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- All Required js -->
    <!-- ============================================================== -->
    <script src="assets/libs/jquery/dist/jquery.min.js "></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="assets/libs/popper.js/dist/umd/popper.min.js "></script>
    <script src="assets/libs/bootstrap/dist/js/bootstrap.min.js "></script>
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
</body>

</html>

Inventory/Views/Shared/_Footer.cshtml
<footer class="footer text-center text-muted">
    2025 -  <a href="https://inovasicode.com">Inovasicode.com</a>.
</footer>

Inventory/Views/Shared/_Navbar.cshtml
@using System.Security.Claims

<nav class="navbar top-navbar navbar-expand-md">
    <div class="navbar-header" data-logobg="skin6">
        <!-- This is for the sidebar toggle which is visible on mobile only -->
        <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)">
            <i class="ti-menu ti-close"></i>
        </a>
        <!-- ============================================================== -->
        <!-- Logo -->
        <!-- ============================================================== -->
        <div class="navbar-brand">
            <!-- Logo icon -->
            <a href="/">
                <span class="logo-text">
                   InventoryApp
                </span>
            </a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Toggle which is visible on mobile only -->
        <!-- ============================================================== -->
        <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)"
           data-toggle="collapse" data-target="#navbarSupportedContent"
           aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="ti-more"></i>
        </a>
    </div>
    <!-- ============================================================== -->
    <!-- End Logo -->
    <!-- ============================================================== -->
    <div class="navbar-collapse collapse" id="navbarSupportedContent">
        <!-- ============================================================== -->
        <!-- toggle and nav items -->
        <!-- ============================================================== -->
        <ul class="navbar-nav float-left mr-auto ml-3 pl-1">
            <!-- Notification -->
            <li class="nav-item dropdown">
                
                <div class="dropdown-menu dropdown-menu-left mailbox animated bounceInDown">
                    <ul class="list-style-none">

                    </ul>
                </div>
            </li>
            <!-- End Notification -->
            <!-- ============================================================== -->
            <!-- create new -->
            <!-- ============================================================== -->
            <li class="nav-item dropdown">
               
            </li>
            <li class="nav-item d-none d-md-block">
               
            </li>
        </ul>
        <!-- ============================================================== -->
        <!-- Right side toggle and nav items -->
        <!-- ============================================================== -->
        <ul class="navbar-nav float-right">
            <!-- ============================================================== -->
            <!-- Search -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- User profile and search -->
            <!-- ============================================================== -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="javascript:void(0)" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <img src="/assets/images/users/profile-pic.jpg" alt="user" class="rounded-circle"
                         width="40">
                    <span class="ml-2 d-none d-lg-inline-block">
                        <span>Hello,</span> <span class="text-dark">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <span>@User.Identity.Name - @User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value </span>
                            }
                            else
                            {
                                <span>Guest</span>
                            }

                        </span> <i data-feather="chevron-down" class="svg-icon"></i>
                    </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item logout-btn" href="javascript:void(0)">
                        <i data-feather="power" class="svg-icon mr-2 ml-1"></i>
                        Logout
                    </a>
                </div>

            </li>
            <!-- ============================================================== -->
            <!-- User profile and search -->
            <!-- ============================================================== -->
        </ul>
    </div>
</nav>

Inventory/Views/Shared/_Sidebar.cshtml
<nav class="sidebar-nav">
    <ul id="sidebarnav">
        <li class="sidebar-item">
            <a class="sidebar-link sidebar-link" asp-controller="Home" asp-action="index"
               aria-expanded="false">
                <i data-feather="home" class="feather-icon"></i><span class="hide-menu">Dashboard</span>
            </a>
        </li>
      
        @if(User.IsInRole("superadmin"))
        {
            <li class="list-divider"></li>
            <li class="nav-small-cap"><span class="hide-menu">Master Data</span></li>
            <li class="sidebar-item">
                <a class="sidebar-link has-arrow" href="javascript:void(0)"
                   aria-expanded="false">
                    <i data-feather="layers" class="feather-icon"></i><span class="hide-menu">Master Data </span>
                </a>
                <ul aria-expanded="false" class="collapse  first-level base-level-line">
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-controller="Item" asp-action="index">
                            <span class="hide-menu">
                                Items
                            </span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-controller="Category" asp-action="index">
                            <span class="hide-menu">
                                Categories
                            </span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-controller="Unit" asp-action="index">
                            <span class="hide-menu">
                                Units
                            </span>
                        </a>
                    </li>

                </ul>
            </li>

            <li class="list-divider"></li>
            <li class="nav-small-cap"><span class="hide-menu">Company</span></li>
            <li class="sidebar-item">
                <a class="sidebar-link has-arrow" href="javascript:void(0)"
                   aria-expanded="false">
                    <i data-feather="bookmark" class="feather-icon"></i><span class="hide-menu">Company </span>
                </a>
                <ul aria-expanded="false" class="collapse  first-level base-level-line">
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-controller="Supplier" asp-action="index">
                            <span class="hide-menu">
                                Suppliers
                            </span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-controller="Customer" asp-action="index">
                            <span class="hide-menu">
                                Customers
                            </span>
                        </a>
                    </li>

                </ul>
            </li>
        }

        @if (User.IsInRole("superadmin") || User.IsInRole("admin"))
        {
            <li class="list-divider"></li>
            <li class="nav-small-cap"><span class="hide-menu">Transaction</span></li>
            <li class="sidebar-item">
                <a class="sidebar-link sidebar-link" asp-controller="IncomingItem" asp-action="index"
                   aria-expanded="false">
                    <i data-feather="arrow-right-circle" class="feather-icon"></i><span class="hide-menu">Incoming Items</span>
                </a>
            </li>
            <li class="sidebar-item">
                <a class="sidebar-link sidebar-link" asp-controller="ItemOut" asp-action="index"
                   aria-expanded="false">
                    <i data-feather="arrow-left-circle" class="feather-icon"></i><span class="hide-menu">Items Out</span>
                </a>
            </li>

            <li class="list-divider"></li>
            <li class="nav-small-cap"><span class="hide-menu">Report</span></li>
            <li class="sidebar-item">
                <a class="sidebar-link sidebar-link" asp-controller="ItemStockReport" asp-action="index"
                   aria-expanded="false">
                    <i data-feather="database" class="feather-icon"></i><span class="hide-menu">Items Stock Report </span>
                </a>
            </li>
            <li class="sidebar-item">
                <a class="sidebar-link sidebar-link" asp-controller="IncomingItemReport" asp-action="index"
                   aria-expanded="false">
                    <i data-feather="file-plus" class="feather-icon"></i><span class="hide-menu">Incoming Items Report </span>
                </a>
            </li>
            <li class="sidebar-item">
                <a class="sidebar-link sidebar-link" asp-controller="ItemOutReport" asp-action="index"
                   aria-expanded="false">
                    <i data-feather="file-minus" class="feather-icon"></i><span class="hide-menu">Items Out Report</span>
                </a>
            </li>
        }
    </ul>
</nav>